# Dependencies
markdown:	kramdown
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		André F. Viana
tagline:	'Design & Code for web & mobile'
description:	'I create beautiful, yet functional experiences for both the web and mobile.'
url:		http://dehviana.github.io
comments: true
commentsystem:	disqus
disqus:		andre_viana

author:
  name:		'André L. Ferreira Viana'
  url:		https://twitter.com/alfv_

paginate:	5

# Custom vars
icon:		/assets/images/icon2.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/alfv_
    desc:	Siga-me no twitter

  - icon:	github
    url:	https://github.com/dehviana
    desc:	Acesse meu github

  - icon:	feed
    url:	http://dehviana.github.io/atom.xml
    desc:	Inscreva-se no meu feed
    
menu:
  - title:	Home
    url:	/
    
  - title:	Sobre
    url:	/sobre.html


copyright:
  author:	André L. Ferreira Viana
  url:		http://alfv.com.br
  type_title:	Alguns direitos reservados
  type_url:	http://creativecommons.org/licenses/by-nc/2.5/br
